name: ERBPlugin
version: 0.1
main: ch.kg9dh.main.ERB
commands:
  erb:
    description: Main ERB command.
    usage: /<command> <args>
    default: op
  rap:
    description: Rap something.
    usage: /<command>  
    default: op
  vote:
    description: Vote for a player.
    usage: /<command>  
    default: op